### PR TITLE
Scan Semi-Fix

### PR DESCRIPTION
**Pull request by DarkCeptor44**
This is my first PR ever, it simply catches the timeout error when the user does `lgtv scan` allowing the rest of the code to run and return the fail object string, I'm trying to fix it entirely in the meantime but no luck.
#55 This is the issue I opened related to this semi-fix.

### CODE REVIEW

**Comment by gsantner** [comment]
I cannot confirm that this is a working fix, see:

screenrecord

Also, at points where it works, it says 0 devices (though other software can see the device). Seems not like it even scans or waits for response.

**Comment by DarkCeptor44** [comment]
My bad I shouldn't have called it a semi-fix, all it does is catch the error as it's good practice.
The socket timeout error is still being thrown even though the code seems correct, I tried with 15s of timeout instead of 1 or 2 but all it does is throw the error 15 seconds later rather than instantly.

**Comment by gsantner** [comment]
no worries, just wanted to say it doesnt work well for me :D

**Comment by klattimer** [comment]
This is probably a dead branch, please retest your issue and report back (I've just merged up a bunch of changes, not even certain the status of master :) )

**Comment by gsantner** [comment]
@klattimer 
I used instructions from project readme  last week and got the error described in PR.

**Comment by klattimer** [comment]
I just updated the code.

**Pull request closed without merging**
