### PR TITLE
small fix if auth fails & comment about using arp

### PR DESCRIPTION
**Pull request by LaggAt**
I also had isues using the IP-address, I needed to use hostname and working dns.

### CODE REVIEW

**Comment by klattimer** [comment]
Regarding the ipaddress problem, I've only used ip addresses and it worked fine, so that's interesting... I'll take a look at it if I can reproduce the results.

**Comment by LaggAt** [comment]
Sry, didn't read your answer. I'll replace the else as soon as I am on that machine again. 
Regarding IP-Address: do you have reverse-DNS working? I havn't, so this could cause the issue.

Shall we add an empty example config just in case scan and auth doesn't work?

**Comment by LaggAt** [comment]
Please review again. Thanks.

**Comment by klattimer** [comment]
I think what we need to do is detect if the supplied host is an IP and only resolve the hostname if it's a hostname. 

Maybe if you experiment with your setup it would be best, I do have reverse DNS working.

**Pull request merged**
